export const ENGLISH: {name: string, value: string}[] = [
  {name: 'login', value: 'Login'},
  {name: 'userName', value: 'User name'},
  {name: 'questions', value: 'Questions'},
  {name: 'question', value: 'question'},
  {name: 'nobodyAskedMessage', value: 'Nobody asked any question yet!'},
  {name: 'homePage', value: 'Home'},
  {name: 'newQuestion', value: 'New Question'},
  {name: 'logout', value: 'Logout'},
  {name: 'description', value: 'description'},
  {name: 'add', value: 'add'},
  {name: 'details', value: 'details'},
  {name: 'asked', value: 'asked'},
  {name: 'wrote', value: 'wrote'},
  {name: 'accept', value: 'accept'},
  {name: 'newAnswer', value: 'new answer'},
  {name: 'answer', value: 'answer'},
  {name: 'changeLanguage', value: 'Váltás magyarra'},
];
