export const HUNGARIAN: {name: string, value: string}[] = [
  {name: 'login', value: 'Bejelentkezés'},
  {name: 'userName', value: 'Felhasználónév'},
  {name: 'questions', value: 'Kérdések'},
  {name: 'question', value: 'kérdés'},
  {name: 'nobodyAskedMessage', value: 'Senki sem kérdezett még!'},
  {name: 'homePage', value: 'Kezdőoldal'},
  {name: 'newQuestion', value: 'Új kérdés'},
  {name: 'logout', value: 'Kilépés'},
  {name: 'description', value: 'leírás'},
  {name: 'add', value: 'hozzáad'},
  {name: 'details', value: 'Részletek'},
  {name: 'asked', value: 'kérdezte'},
  {name: 'wrote', value: 'írta'},
  {name: 'accept', value: 'elfogad'},
  {name: 'newAnswer', value: 'új válasz'},
  {name: 'answer', value: 'válasz'},
  {name: 'changeLanguage', value: 'Change to english'},
];
